config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
   <div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="/restaurants" class="navbar-wagon-item navbar-wagon-link">Home</a>
    <a href="/restaurants/new" class="navbar-wagon-item navbar-wagon-link">Create</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Login</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/restaurants">Home</a></li>
        <li><a href="/restaurants/new">Create</a></li>
        <li><a href="#">Login</a></li>
      </ul>
    </div>
  </div>
</div>

    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w(chinese italian japanese french belgian)%>

  <%= f.submit "Save the Restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container jumbotron">

<h1> Edit the Restaurant: <%=@restaurant.name%></h1>

<%= render 'form', restaurant: @restaurant %>


<hr>

<%= link_to("Back to restaurants", restaurants_path, class:"btn btn-primary") %>



</div>

app/views/restaurants/index.html.erb
<div class="container jumbotron">

<h1>My list of restaurants</h1>

<hr>

  <ul class="list-group">
  <% @restaurants.each do |restaurant| %>
  <li class="list-group-item">
    <%= link_to(restaurant.name, restaurant_path(restaurant)) %>
    <%= restaurant.address %>
    <%= restaurant.category %>
  </li>
  <% end %>
  </ul>
  <hr>


<%= link_to('New Restaurant', new_restaurant_path, class:'btn btn-success btn-lg')%>


</div>

</div>

app/views/restaurants/new.html.erb
<div class="container jumbotron">

<h1> Create a new restaurant</h1>

<%= render 'form' %>


<hr>

<%= link_to("Back to index", restaurants_path, class:"btn btn-primary") %>



</div>

app/views/restaurants/show.html.erb
<div class="container jumbotron">
<h1>Task: <%= @restaurant.name %></h1>
<hr>
<h3>Address: <%= @restaurant.address %></h3>

<hr>

<p>Phone number: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>

<hr>

<ul>
Reviews: <% @restaurant.reviews.each do |review| %>
<li> <p> <%= review.content %> --- Rating : <%= review.rating %> / 5</p> </li>
<% end %>
</ul>





<hr>
<%= link_to("Add a new review", new_restaurant_review_path(@restaurant), class:"btn btn-primary") %>

<%= link_to("Back to restaurants", restaurants_path, class:"btn btn-primary") %>


<%= link_to("Edit the restaurant", edit_restaurant_path(@restaurant), class:"btn btn-success") %>

</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review = Review.new] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: %w(0 1 2 3 4 5) %>

  <%= f.submit "Save the review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<div class="container jumbotron">

<h1> Create a new review</h1>

<%= render 'form' %>


<hr>

<%= link_to("Back to the restaurant", restaurant_path(@restaurant), class:"btn btn-primary") %>



</div>